---
# tasks file for ec2
- name: create S3 bucket
  s3_bucket:
    name: ec2bucket
    policy: "{{ lookup( 'file','ec2_bucket_policy.json' )}}"
    state: "{{ state }}"
    region: "{{ region }}"
    versioning: no
    tags:
      name: ec2bucket
      type: titile
